### ISSUE TITLE
AppImages don't run

### ISSUE THREAD

**Issue by DutchPete** [rollingrhinoremix/docs#1]
I downloaded the AppImage for KeepassXC and for Obsidian, and I have the AppImageLauncher installed.
Clicking on either KeepassXC or Obsidian in the main menu does nothing, nor does clicking on the AppImages in the Applications folder.

I deleted the KeepassXC AppImage and installed the app via pacstall. The donload of packages took a bit of time, but when it was done and the app installed, it worked.

So, what to do about Obsidian, which is not in pacstall?

**Comment by ajstrongdev** [comment]
Hello, I will need a bit more information. What happens if you try to run the AppImage inside of the terminal?

**Comment by DutchPete** [comment]
RRR was experimental for me. I did not like the fact that any software I installed was done with a Snap. There was also that incessant message coming up about something missing/not right in Ubuntu 22.04.

And finally, I was disappointed to get no answer to the AppImage issue after 5 days. So, I moved on to another distro where things work, there is a very helpful, responsive community, and the range of software on offer is impressive.

**Comment by ajstrongdev** [comment]
> RRR was experimental for me. I did not like the fact that any software I installed was done with a Snap. There was also that incessant message coming up about something missing/not right in Ubuntu 22.04.
> 
> Ad finally, I was disappointed to get no answer to the AppImage issue after 5 days. So, I moved on to another distro where things work, there is a very helpful, responsive community, and the range of software on offer is impressive.

I am glad you found a distro you like, and I am sorry that Rolling Rhino Remix did not satisfy you. You can also install Flatpak for more additional software or make use of Pacstall and the official repositories.

**Comment by DutchPete** [comment]
When I learned about Pacstall, I was very excited about it. When I looked at what is in there, I was very disappointed indeed, it is miles behind AUR.

As for Flatpaks, big and slow. No thanks.

I am sorry I cannot be more positive, but TBH I was disappointed by what I found. I know the distro is still in beta, but to me a beta version should still be more polished than what RRR is at the mo; to me RRR is alpha+.

**Comment by ajstrongdev** [comment]
>Pacstall is in constant development and it is miles ahead of other debian solutions for the AUR. The Pacstall developers are working on Pacstall v2.0 and it is improving their system massively.

>Flatpaks utilise shared libraries and so while the initial installation of a few Flatpaks are large, they become smaller over time since they share libraries across them. As for them being slow, they run at near-native speeds and offer some of the best solutions to application packaging and security. 

>Rolling Rhino Remix is in neither Alpha nor Beta. AppImages have ran perfectly fine on my system and so the likely culprit is a dodgy AppImage. I tested an AppImage and it functioned as intended. We are creating this distribution for free and on a volunteer basis, the best way to improve it is to contribute. We do not have a lot of free time and any time we do get is spent improving upon and working on the distribution.

**Comment by Elsie19** [comment]
> When I learned about Pacstall, I was very excited about it. When I looked at what is in there, I was very disappointed indeed, it is miles behind AUR.
> 
> As for Flatpaks, big and slow. No thanks.
> 
> I am sorry I cannot be more positive, but TBH I was disappointed by what I found. I know the distro is still in beta, but to me a beta version should still be more polished than what RRR is at the mo; to me RRR is alpha+.

What part of Pacstall made you disappointed?

**Comment by DutchPete** [comment]
@Chadano : “miles ahead of other debian solutions for the AUR”
I don't understand that statement: AUR is not for Debian solutions.

Flatpaks may be better than Snaps and many people like them; I have read that they are big and slow. I do not have experience with Flatpaks but at this stage I won't try.

I learned about RRR a couple of weeks ago in a write up on DistroWatch, and in there it is referred to as still in beta.

No, the AppImage I referred to was not dodgy, it worked fine in other distros I tried. It was KeepassXC BTW.

I understand the distro is free and done by volunteers with limited spare time, I have no issues with that per se, I have not criticized that. But I do want to have a distro I feel comfortable with and which offers me what I am looking for. An important part of that is an *active* forum. I say active because there are distros that have a forum but where activity is low, so like here, one has to wait for days to get a response, if at all.

I had no preconceived ideas about RRR so I gave it a shot; I was not satisfied.

**Comment by DutchPete** [comment]
@Henryws: what disappointed me about Pacstall was the paucity of apps, as I stated in an earlier comment above. iirc, I managed to find only 1 of the apps I use regularly (cannot remeber which one), and those I did not find are not highly unusual, niche apps.

**Comment by Elsie19** [comment]
Considering the AUR began in 2004, and pacstall began in 2020, obviously there will be a difference in packages.

And even so, you could have just made a pacscript for your apps (they're incredibly easy to make). I'm doing this is my free time, and pacstall is worth every penny you pay for it 😁

**Comment by DutchPete** [comment]
@Henryws: sure, it is understandable, but the big discrepancy is there, it is a fact.
And like I pointed out, there are other reasons why I was not satisfied with RRR.

**Comment by ajstrongdev** [comment]
Rolling Rhino Remix does have an active chat where I am much more active. It's hosted on Matrix or Discord and you will be able to talk to me there as I am active pretty much 24/7 excluding sleep. Rather than waiting days you may have to wait 4-8 hours at the most.
