### ISSUE TITLE
Make it clear to not run rhino-init or rhino-update as root

### ISSUE THREAD

**Issue by mcassaniti** [rollingrhinoremix/docs#2]
When I first logged into a new minimal setup I ran `sudo -s` to get to root and was surprised that I couldn't find `rhino-init` or `rhino-update`. Eventually I found out that these are bash aliases and I should've ran them straight up as the user I setup during installation. Could the documentation be updated to cover this **or** the aliases be added for the root user also?

I know, probably a rookie mistake.

**Comment by ajstrongdev** [comment]
> When I first logged into a new minimal setup I ran `sudo -s` to get to root and was surprised that I couldn't find `rhino-init` or `rhino-update`. Eventually I found out that these are bash aliases and I should've ran them straight up as the user I setup during installation. Could the documentation be updated to cover this **or** the aliases be added for the root user also?
> 
> I know, probably a rookie mistake.

When our documentation says to run something, it should be ran exactly as shown.
